### ISSUE TITLE
Link de "React: De aprendiz a maestro" no funciona

### ISSUE THREAD

**Issue by NicolasBlasquez** [midudev/libros-programacion-gratis#8]
> El link de "React: De aprendiz a maestro", de Raúl Expósito, lleva a un error 404

![Captura de pantalla 2024-02-19 000348](https://github.com/midudev/libros-programacion-gratis/assets/87918334/90b2c478-c90a-426f-bb84-a98a3528c3d2)

**Comment by midudev** [comment]
Arreglado!
